# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-15 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_code', models.CharField(max_length=255)),
                ('addons', models.ManyToManyField(related_name='available_addons', to='chat.Addons')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Company')),
            ],
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='details',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='needs',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='pref',
        ),
        migrations.AddField(
            model_name='insurance',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='idv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='premium',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='thirdparty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='addons',
            field=models.ManyToManyField(related_name='choosed_addons', to='chat.Addons'),
        ),
    ]
