# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-15 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20181215_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Vehicle'),
        ),
    ]
