# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-15 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_insurance_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='thirdparty',
        ),
        migrations.AddField(
            model_name='insurance',
            name='insurance_type',
            field=models.ManyToManyField(related_name='insurance_type', to='chat.InsuranceType'),
        ),
    ]
