# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-15 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20181215_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='{}')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.AgentInfo')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_data',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='conversations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.UserInfo'),
        ),
    ]
